### ISSUE TITLE
Wiring for Rain Sensor <-> GPIO33?

### ISSUE THREAD

**Issue by fake666** [hugokernel/esphome-rain-detector#1]
Hi, 

first of all, thanks for sharing! The issue here is not with your project, but with me: I'm looking into hooking my rain sensor up like you did, but i'm a bit of a noob when it comes to wiring this up...

could you share a schematic of how you connected the rain sensor to the esp32? i guess it needs some voltage so the ADC has something to measure, but you mention you only power it every 5 seconds, and that's where i get mentally stuck already XD

thanks in advance!

fake

**Comment by hugokernel** [comment]
Hi Thomas,

Start on the same configuration explained on the [Resistance integration page](https://esphome.io/components/sensor/resistance.html) but instead of wiring directly resistance (the sensor) on 5V, connect it on `Resistance BIAS` (GPIO 19).

If you wiring direclty on 5V, it will be working but use more power and will damage the sensor prematurely. 

I will make a diagram when I have some time.

++

**Comment by fake666** [comment]
aaaah... got it. thanks! :D

**Comment by dougiteixeira** [comment]
Some pictures to illustrate sensor connection.

@hugokernel, Thank you for sharing code.

![C1](https://user-images.githubusercontent.com/31328123/150330232-42bf0e46-7078-497e-bab4-b9174544da16.png)

![C2](https://user-images.githubusercontent.com/31328123/150330235-11cc65bc-f99b-418d-909a-e9ff1b7642b6.png)

![C3](https://user-images.githubusercontent.com/31328123/150330239-8e02960b-263e-425d-a9ae-b6b02c320f13.png)

![circuit_rain_detector](https://user-images.githubusercontent.com/31328123/150625969-7349eaef-e9ed-4ce4-88c4-b63340b1c4b2.png)
